histoire-dev/histoire

packages/histoire-plugin-nuxt/src/index.ts
This adds a couple of extra sections of the Nuxt vite config, particularly the `define` section which will replace `process.dev`, `process.server`, `process.client`, etc., which are frequently used in Nuxt projects.
This partially addresses #107, but we now still have a missing `RouterLink` that either needs to be stubbed or imported:
The following is the [minimal `RouterLink` implemented by Nuxt when vue-router is not present](https://github.com/nuxt/framework/blob/cad4edd5a396c447ad99f4016bc856e197c9d85b/packages/nuxt/src/app/plugins/router.ts#L178-L182):
```js
const RouterLink = {
functional: true,
props: { to: String },
setup: (props, { slots }) => () => h('a', { href: props.to, onClick: (e) => { e.preventDefault(); router.push(props.to) } }, slots)
}
```
---
=> fix(nuxt): add additional sections of nuxt vite config

docs/guide/vue3/controls.md
Remove setup attribute from options api.
---
=> docs: fix options api example

docs/guide/config.md
=> sanbox -> sandbox typo fix

packages/histoire/src/client/app/util/sandbox.ts, packages/histoire/src/node/build.ts
Fix for #141
Ensure URL matches the actual filename used for `__sandbox.html`
---
=> fix: use __sandbox.html instead of __sandbox, fix #141

docs/.vitepress/config.js, docs/guide/plugins/development.md, docs/guide/plugins/official.md, docs/reference/config.md
Resolves #170.
I created a new directory `plugins` to store the splitted pages, in reference to `vue3` directory.
---
=> docs: split plugins page, fix #170

packages/histoire-plugin-percy/README.md
fixes: #296
I fixed `histoire-plugin-percy`'s Readme.md typo https://github.com/histoire-dev/histoire/blob/main/packages/histoire-plugin-percy/README.md?plain=1#L3
nothing
---
=> docs: fix typo Perci -> Percy

docs/reference/config.md
The documentation was referring to an old usage of the NuxtPlugin as plugin example. It is now updated to match current usage.
---
=> docs(histoire): use a more pertinent example in #plugins

packages/histoire-app/src/app/style/main.pcss, packages/histoire-app/src/app/style/sandbox.css, packages/histoire-controls/src/components/HstWrapper.vue, packages/histoire-controls/src/components/button/HstButton.story.vue, packages/histoire-controls/src/components/button/HstButton.vue, packages/histoire-controls/src/components/button/HstButtonGroup.story.vue, packages/histoire-controls/src/components/button/HstButtonGroup.vue, packages/histoire-controls/src/components/number/HstNumber.vue, packages/histoire-controls/src/components/slider/HstSlider.story.vue, packages/histoire-controls/src/index.ts, packages/histoire-plugin-svelte/src/index.ts
Add Button and ButtonGroup control components
=> feat: add buttons controls

.github/ISSUE_TEMPLATE/bug-report.yml
A Svelte/histoire template should be provided in the bug report template, to resolve better Svelte bug reports.
The url is still quite ulgy with a https://stackblitz.com/edit/ `node-guobd` in the middle of it.
---
=> chore: added starter sveltekit/histoire to bug report template

docs/guide/vue3/controls.md
=> docs(controls): fix content reference

docs/examples/tailwind.md
This PR fixes a minor typo in the documentation.
=> docs: fix typo

docs/guide/svelte3/stories.md
=> docs: typo about svelte <script>

docs/guide/vue3/controls.md
=> docs: fix vue3 guide doc demo code (#377)

packages/histoire-plugin-svelte/src/client/util.ts
=> fix: missing null check #389

docs/guide/plugins/official.md
Adds the Svelte plugin to the list of official plugins
---
=> docs: add Svelte plugin to list of official plugins

packages/histoire/src/node/builtin-plugins/pinceau-tokens.ts
Follow up of https://github.com/histoire-dev/histoire/pull/308
This PR only includes the file that allows to render Pinceau theme and browse it as a design system.
Previous PR was touching too much files so I reduced this as much as possible.
I'll provide the Histoire examples from Pinceau repository.
---
=> feat(pinceau): support Pinceau as Design System

packages/histoire-app/src/app/components/panel/StoryDocs.vue
fix(docs): header anchors error when hash is chinese. fixes #460
---
=> fix(docs): header anchors error when hash is chinese. fixes #460

packages/histoire-plugin-svelte/src/helpers.ts
Add step prop types for Number and Slider controls
---
=> fix(svelte): Supplement missing member types

packages/histoire-controls/src/components/select/HstSelect.vue
Change v-model type to any
https://github.com/histoire-dev/histoire/commit/1e198a80d8c873008d8bee169bdabac84c15ad0e
=> feat(HstSelect): change `v-model` type to any

docs/reference/config.md
=> docs(config): add info about ionic binary files error

packages/histoire/src/node/tree.ts
=> refactor: more readable code for tree config

packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts
Add support for Tailwind token with opacity modifier syntax color.
Fixed #526 
Tailwind CSS variables color:
https://tailwindcss.com/docs/customizing-colors#using-css-variables
source:
https://github.com/tailwindlabs/tailwindcss/blob/759a8c2061fbb9aabd0ec9c5f534652e7a2c9717/src/util/pluginUtils.js#L107-L115
---
=> feat: tailwind tokens support opacity modifier syntax color (fixed #526)

packages/histoire/src/node/build.ts, packages/histoire/src/node/collect/index.ts, packages/histoire/src/node/config.ts
I added some plural and singular forms for console outputs.
---
=> style: Fixed typos in Console logs

packages/histoire-plugin-nuxt/src/index.ts, pnpm-lock.yaml
Fixes #527 
The error was happening on a project I'm working on, and it seems to be occurring with some other people, but I wasn't able to reproduce it on the examples directory.
The fix is based on @nashtonentwined's [implementation](https://github.com/histoire-dev/histoire/issues/527#issuecomment-1650154728)
=> fix(nuxt): nuxt plugin error (fix #527)

docs/examples/tailwind.md
If you will follow docs you will get an error "Error: Failed to load url virtual:$histoire-setup"
---
=> docs: Fixed file extenssion in docs

.github/ISSUE_TEMPLATE/bug-report.yml
=> docs(github): add a link to `Nuxt Stackblitz` to bug report template (fixes #471)

docs/.vitepress/config.js, docs/examples/visual-regression-testing/lost-pixel.md, docs/examples/visual-regression-testing/percy.md, docs/guide/index.md
Extending the docs with visual regression testing examples for Percy & Lost Pixel
---
=> docs: Add visual regression testing section to the examples

packages/histoire-app/package.json, packages/histoire-plugin-percy/package.json, packages/histoire-plugin-screenshot/package.json, packages/histoire-plugin-svelte/package.json, packages/histoire-plugin-vue/package.json, packages/histoire-shared/package.json, pnpm-lock.yaml
=> fix: Update pathe dependencies everywhere

packages/histoire-plugin-nuxt/runtime/composables.mjs
Solves https://github.com/histoire-dev/histoire/issues/657
Expanding the Nuxt stub a little solves a problem using Histoire with @nuxtjs/i18n
---
=> fix: fixes #657

docs/examples/visual-regression-testing/lost-pixel.md
Update the the lost-pixel documentation file by fixing the typo in the label of Lost Pixel Platform
---
=> docs(lost-pixel): typo in the label
