docs/reference/config.md, packages/histoire/src/node/collect/index.ts, packages/histoire/src/node/config.ts
Closes #108
I've added ViteNode's workaround for processing files under `web` flag (`ssr: false`). By default, most of the files are processed with `ssr: true`.
---
=> feat: add viteNodeTransformMode config option, fix #108

packages/histoire-controls/src/style/main.css, packages/histoire/src/client/app/components/base/BaseSplitPane.vue, packages/histoire/src/client/app/style/main.pcss, packages/histoire/src/client/app/style/sandbox.css, packages/histoire/tailwind.config.cjs
The browser's font resizing feature is one of the commonly used accessibility features. And it is disabled when the font size is set to `px`. The workaround is rem which uses root-based size units .
The change before and after the modification when I resized the font to extra large.
<table>
<tr><td>
</td>
<td>
</td></tr></table>
=> fix(a11y): make font-size follow user brower settings

examples/vue3/src/components/ComplexParameter.story.vue, examples/vue3/src/components/ComplexParameter.vue, packages/histoire/src/client/app/codegen/serialize-js.ts, packages/histoire/src/client/app/components/panel/StatePresets.vue, packages/histoire/src/client/app/util/state.ts
Fix #118 
It's a very simple check to avoid tree-walking recursive objects. We could do a bit better (like stopping when it references something that has already been walked), but I'm not sure if it's worth the trouble...
---
=> fix: recursive object analysis (fix #118)

examples/vue3-percy/src/histoire.css, examples/vue3-screenshot/src/histoire.css, examples/vue3/src/components/Controls.story.vue, examples/vue3/src/histoire.css, packages/histoire-controls/src/components/slider/HstSlider.story.vue, packages/histoire-controls/src/components/slider/HstSlider.vue, packages/histoire-controls/src/index.ts
Linked to #30 
Add slider control
I removed some CSS from `histoire.css` files. Not sure what it was meant to do, but it kinda messed with the CSS.
---
=> feat: add slider control, #30

docs/.vitepress/config.js
Fix #161.
Having a quick look, VitePress seems to distinguish `/foo/` and `/foo/index` in terms of path definition.
As a result, `/foo/index` doesn't match meta data of the page corresponding to `/guide/index.md` file.
Another solution is setting it as `/guide/index.md` or `/guide/index.html`, but I believe trailing slash looks best, because other pages' `link` property is defined without file extensions (e.g. `/guide/getting-started`).
By the way, this is my very first contribution to Histoire. 👶 
Thank you for developing such an awesome tool. 🚀 
---
=> docs: fix next link, fix #161

packages/histoire/src/client/app/util/state.ts
The state watcher in `packages/histoire/src/client/app/sandbox.ts` uses `toRawDeep` to send the story state to the app using `Window.postMessage()`. If the state contains a function, `Window.postMessage()` fails with the error `"DOMException: Failed to execute 'postMessage' on 'Window': () => alert("example") could not be cloned."` and the sandbox in the app doesn't show the component.
This PR fixes the issue by stringifying functions within `toRawDeep`.
---
=> fix: stringify functions in `toRawDeep`

examples/vue3/src/components/Controls.story.vue, packages/histoire-controls/src/components/checkbox/HstCheckbox.vue, packages/histoire-controls/src/components/radio/HstRadio.story.vue, packages/histoire-controls/src/components/radio/HstRadio.vue, packages/histoire-controls/src/components/select/CustomSelect.vue, packages/histoire-controls/src/components/select/HstSelect.vue, packages/histoire-controls/src/index.ts, packages/histoire-controls/src/types.ts
As part of https://github.com/histoire-dev/histoire/issues/30 this PR adds a built-in select control <HstRadio />,
I added the possibility of passing the options as an array of objects { label: string, value: string} or as an array of values. Maybe an enhancement could be to pass a prop to define the key and the value, but I didn't want to complicate it. Both examples are available in the local story HstRadio.story.vue
I also added the control to the vue3 examples app
---
=> feat: added radio controls

packages/histoire/src/node/vite.ts
Tried to run histoire with nuxt3 and got that error.
Questionmark after userViteConfig solves the problem and histoire runs fine.
=> Added questionmark to possibly undefined userViteConfig

packages/histoire/src/node/vite.ts
When running histoire on Windows the following error happens:
```
[plugin:vite:import-analysis] Failed to resolve import "D:documentsGitHubhistoirepackageshistoire-plugin-vuedistundledclientclient.js" from "virtual:$histoire-support-plugins-client". Does the file exist?
1  |  export const clientSupportPlugins = {
2  |            'vue3': () => import('D:\documents\GitHub\histoire\packages\histoire-plugin-vue\dist\bundled\client\client.js')
|                                 ^
3  |          }
```
This was happening because `\` was not escaped when quoting with `'`.
This PR uses `JSON.stringify(foo)` instead of `"'" + foo + "'"`.
---
=> fix: resolve plugin correctly on windows

packages/histoire-vendors/rollup.config.mjs
Building `@histoire/vendors` on windows was generating invalid outputs.
**Before**
```ts
import Default from './dist\client\b-pinia'
export default Default
export * from './dist\client\b-pinia'
```
**After**
```ts
import Default from './dist/client/b-pinia'
export default Default
export * from './dist/client/b-pinia'
```
---
=> chore: fix vendors windows build

packages/histoire-app/src/app/components/story/StoryResponsivePreview.vue
When the responsive preview is at 'Auto' width and height, if we try to resize again, the preview immediately snaps to minimum width or height. After the snap `value.value` becomes `null`. During the next resize, the `startValue` takes up this `null`. I guess this is why it is happening.
Now when the snap happens, the resize placeholder shows 'Auto'. And in the next resize, the `startValue` is taken with respect to the current width/height.
=> fix: resize story responsive preview

examples/vue3/cypress/integration/markdown-links.js, examples/vue3/cypress/integration/search.js, examples/vue3/cypress/integration/stories-list.js, examples/vue3/src/components/MarkdownLinks.story.vue, packages/histoire/src/node/markdown.ts
Currently it is not possible to add  internal links starting with `#` as those get `target=_blank` added.
#234 
---
=> fix: do not add target blank to urls that start with # in markdown

docs/guide/svelte3/controls.md
Fix #242 
Just variable naming in [this link](https://histoire.dev/guide/svelte3/controls.html#defining-state). I've considered conserving the variable `text`. But if you prefer `message`, feel free to reject this PR or to ask me to change it. 😁
---
=> docs: fix the variables in the svelte section (fix histoire-dev#242)

package.json, pnpm-lock.yaml
In Histoire docs, the sidenav of Vue 3 -> Controls are towards Vue 2.
In local dev mode, it always works, but after the build, the sidenav information was wrong.
I found that simply upgrading VitePress to the latest version works. So just did that.
---
=> chore: upgrade vitepress

packages/histoire/src/node/commands/dev.ts, packages/histoire/src/node/server.ts, packages/histoire/src/node/vite.ts
Dev port was always 6006 when not defined in the command line
Example histoire config:
```ts
// vite.config.js
/// <reference types="histoire" />
import { defineConfig } from 'vite'
export default defineConfig({
// ...
histoire: {
vite: {
server: {
port: 1980,
},
},
},
})
```
---
=> fix: config dev port (fix #317)

packages/histoire-plugin-svelte/src/client/util.ts
fix #264 
Since `Vue.watch` will use `Proxy` to wrapper svelte component state value, once component state value changed, the global `variantState` changed in the same time which will make `applyState` useless and the `watch` callback not be triggered.
We can use `histoire/shared.clone` to cut the relation between `variantState` and component internal state.
---
=> fix(svelte): variantState should not be modified by component internal state

packages/histoire-app/src/app/components/story/StoryVariantSinglePreviewNative.vue
I found that dark class is not attached when `layout.iframe` option of Story component is false.
This PR fix it.
You can check it on the following stackblitz repo. 
https://stackblitz.com/edit/histoire-vue3-starter-nbze5i?file=src%2FBaseButton.vue
**Step to reproduce**
1. Select the `BaseButton`.
2. Toggle dark mode, then the style of it is not changed. It's expected to change to a dark mode style, just like when iframe is used.
---
=> fix: missing dark class when layout.iframe option is false

docs/reference/config.md
There's no longer a plugin named `vite-plugin-svelte-kit`. Also, users should not need to set this to use SvelteKit with Histoire so I just changed it to a generic example.
---
=> docs: remove reference to plugin that no longer exists

packages/histoire-controls/src/components/button/HstButtonGroup.vue, packages/histoire-controls/src/components/checkbox/HstCheckboxList.vue, packages/histoire-plugin-vue/components.d.ts
Add types components in global components
Add type string[] in HstButtonGroup, HstCheckboxList
---
=> fix: missing types components in global components

packages/histoire-plugin-svelte/src/index.ts
`@histoire/plugin-svelte` seems to wrongfully use `TextArea` instead of `Textarea` on the exported `Hst` interface. ([Demo](https://stackblitz.com/edit/sveltejs-kit-template-default-g4v5ov))
---
=> fix(svelte-control-elements): textarea capitalization typo on interface

docs/guide/svelte3/getting-started.md
Fixed a simple typo in the Svelte getting started docs. 
> Histoire provides two commands:
> [3 commands]
I changed `two` to `three`
https://histoire.dev/guide/svelte3/getting-started.html
---
=> docs(svelte): correct a typo in the svelte getting started docs

docs/reference/client.md, docs/reference/config.md, package.json, packages/histoire-app/src/app/api.ts, packages/histoire-app/src/app/components/app/AppHeader.vue, packages/histoire-app/src/app/util/dark.ts, packages/histoire-controls/package.json, packages/histoire-shared/src/types/config.ts, packages/histoire-vendors/package.json, packages/histoire/client.d.ts, packages/histoire/src/node/config.ts, pnpm-lock.yaml
Fix #388
New configuration options:
```js
export default defineConfig({
theme: {
defaultColorScheme: 'light',
hideColorSchemeSwitch: true,
storeColorScheme: false,
},
})
```
New client API:
```js
import { isDark, toggleDark } from 'histoire/client'
if (isDark()) {
// do something only in dark mode
}
toggleDark()
toggleDark(true)
```
=> feat: Dark mode API and config, fix #388 (#438

examples/nuxt3/cypress/e2e/render-story.cy.js, packages/histoire-plugin-nuxt/runtime/app-component.mjs, packages/histoire-plugin-nuxt/src/index.ts
Fixes #472
This PR stops `@histoire/plugin-nuxt` from rendering whatever is in nuxt `app` template under each story and the whole histoire page itself. 
It does so by injecting an empty compiled vue template instead of the app template.
It also disables `pages` in `nuxt.config` for the plugin not to try rendering the app routes, which avoids `vue-router` errors in console and the rendering of `404s` in place of the extra app template.
Please tell me if i should write a test that checks that nuxt `app` template / `404s` don't render alongside stories.
Perhaps by checking there's no additional content instead of looking for specific content.
---
=> fix(nuxt): do not render app pages alongside stories (fixes #472)

packages/histoire/src/node/collect/index.ts
Ensuring that `threadsCount` results in an integer rather than a double when cpus is an odd number.
Fixes #469
No additional context.
---
- [] If it's a new feature, provide a convincing reason to add it. *Ideally, you should open a suggestion issue first and have it approved before working on it.*
- [] Ideally, include relevant tests that fail without this PR but pass with it.
=> fix: Ensuring that `threadsCount` results in an integer rather than a double when cpus is an odd number. (Fixes #469 )

packages/histoire/src/node/markdown.ts
Setting `breaks: false` in `MarkdownIt` default config. This is default MD behavior on GitHub as well as other platforms.
The reason for this is to allow people to write Story docs in their editor and not have to write a really long single line to achieve soft wraps. Before this PR, if you did this:
```html
<docs lang="md">
A simple menu component that displays a list of items in a dropdown menu. You
can supply an array of items that include the label, icon, optional color, and
action callback.
</docs>
```
It would force wrap at those points, which might look bad in some scenarios:
---
=> fix(MD)!: Set breaks to false in Markdown (default behavior)

packages/histoire-vendors/rollup.config.mjs
Fix #504 
It seems like `npm` is having a hard time resolving dependencies of `floating-vue`.
(I have npm 9.6.2 and pnpm 8.1.0)
I just added the "--legacy-peer-deps" to allow the build of histoire-vendors.
---
=> fix: histoire-vendors broken build

packages/histoire-controls/src/components/checkbox/HstCheckbox.story.vue, packages/histoire-controls/src/components/checkbox/HstCheckbox.vue
Fix #502 
I added the string value "true" and "false" to possible value of HstCheckbox.
I think it's a good idea to add this feature since having a toggle between "true" and "false" is a valid concern.
If you think it's useless, feel free to close the PR.
- Is the value is a string, it will be updated to a string
- By default, any string value which is not "false" is considered "true" (but expected input types are "true" or "false" anyway)
---
=> feat: Add booleanish checkbox

packages/histoire-plugin-nuxt/package.json, packages/histoire-plugin-nuxt/src/index.ts, pnpm-lock.yaml
resolves #508
related: https://github.com/danielroe/nuxt-vitest/pull/130
In Nuxt we moved the injection of vue plugins to _after_ the hook we are using in histoire. (To allow modules to modify the config for them.) This change adds them to Nuxt's vite plugins if they are missing - so it should be backwards compatible.
(Though we might want to make them peer dependencies?)
---
=> fix(nuxt): add vite vue plugins if they are missing

.github/workflows/test-nuxt3.yml, .github/workflows/test-svelte3.yml, .github/workflows/test-vue3.yml, .github/workflows/test.yml, package.json
6c4e4c78755605a28916c339149f51e3a7fd71e1 updated pnpm to 8.6.2 but didn't update the `packageManager` field.
I guess this broke the vite-ecosystem-ci.
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/5330308448/jobs/9656862024#step:8:302
I also removed the version field from the workflows files as the latest pnpm setup action read the `packageManager` field.
---
=> chore: fix pnpm version inconsistency

examples/svelte3/package.json, examples/sveltekit/package.json, examples/vue2/package.json, examples/vue3-percy/package.json, examples/vue3-screenshot/package.json, examples/vue3-themed/package.json, examples/vue3-vuetify/package.json, examples/vue3/package.json, packages/histoire-app/package.json, packages/histoire-controls-stories/package.json, packages/histoire-controls/package.json, packages/histoire-plugin-nuxt/package.json, packages/histoire-plugin-svelte/package.json, packages/histoire-plugin-vue/package.json, packages/histoire-plugin-vue2/package.json, packages/histoire-shared/package.json, packages/histoire/package.json, pnpm-lock.yaml
When linking `vite` locally and running `pnpm test`. There's an error in `packages/histoire`:
```
ERROR  Failed to load url esbuild (resolved id: esbuild). Does the file exist?                                                                              14:23:30
at loadAndTransform (/Users/bjorn/Work/oss/vite/packages/vite/dist/node/chunks/dep-4650b0ed.js:54937:21)
at async ViteNodeServer._transformRequest (/Users/bjorn/Work/oss/histoire/node_modules/.pnpm/vite-node@0.3.6/node_modules/vite-node/dist/server.js:197:16)
at async ViteNodeServer._fetchModule (/Users/bjorn/Work/oss/histoire/node_modules/.pnpm/vite-node@0.3.6/node_modules/vite-node/dist/server.js:185:17)
at async MessagePort.<anonymous> (/Users/bjorn/Work/oss/histoire/node_modules/.pnpm/@peeky+runner@0.14.0/node_modules/@peeky/ru …
```
=> chore: fix ecosystem-ci

examples/svelte3/package.json, packages/histoire-plugin-svelte/package.json, pnpm-lock.yaml
Fixes #551.
I've added version `^4.0.0` for the peer dependency inside the `svelte` histoire plugin to be able to migrate the existing repositories that are using histoire with `svelte` to latest version (^4.0.0).
=> fix(svelte): add `svelte@^4.0.0` peer dependency option for `svelte` plugin (fix #551)

examples/nuxt3/components/AutoImport.story.vue, examples/nuxt3/cypress/e2e/render-story.cy.js, examples/nuxt3/nuxt.config.ts, packages/histoire-plugin-nuxt/src/index.ts, packages/histoire-plugin-nuxt/src/runtime/app-setup.ts
Fixes #494
I've made the setupNuxtApp function to accept the current Nuxt instance's public runtime config that is returned from loadNuxt and also passed in that value into setupCode in an 'eval' like fashion through JSON.stringify.
This should address the issue at hand, but may also fix compatibility issues with other Nuxt modules which may populate the public runtime config as part of their initialisation such as @storyblok/nuxt (I've encountered this issue on another project while attempting to integrate Histoire).
Relevant line: https://github.com/storyblok/storyblok-nuxt/blob/8874551fa331c72921cd4a8279c67089311c5750/src/module.ts#L57
---
=> fix(nuxt): pass nuxt runtimeConfig into nuxt app stub (fix #494)

packages/histoire/src/node/tree.ts
Fixes #276.
Added a conditional for verifying if the tree file path includes ".histoire" which identifies it as being a plugin.
---
=> fix: adjust tree file path if it's a plugin (fix #276)

packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts
Fixes [an issue](https://github.com/histoire-dev/histoire/issues/391) where only one type of value is allowed for configuring `fontSize` in the Tailwind theme. Tailwind [supports](https://tailwindcss.com/docs/font-size#using-custom-values) the following values:
```js
module.exports = {
theme: {
fontSize: {
sm: '0.8rem', // single value
base: ['16px', '24px'], // [fontSize, lineHeight] tuple
'lg': ['1.5rem', {
lineHeight: '2rem',
letterSpacing: '-0.01em',
fontWeight: '500',
}], // [fontSize, { lineHeight?, letterSpacing?, fontWeight? }] tuple
}
}
}
```
---
=> fix(tailwind): allow different fontSize configuration values

packages/histoire/package.json, pnpm-lock.yaml
The `vite-node` of `vitest` fixes a [bug](https://github.com/unocss/unocss/issues/2509) since `v0.31.0` ([commit](https://github.com/vitest-dev/vitest/commit/b1624db5d3baf26f7e1c69b23cf4c1335562ccde)).
This PR updates the `vite-node` to the same version (`^0.34.1`) with `vitest`.
fixes #547
---
=> fix: update `vite-node` version to fix `__vite_ssr_import_meta__ ` error

packages/histoire-plugin-nuxt/src/index.ts
This is an advance fix for Nuxt v3.8, which ships with a new 'app manifest' feature that doesn't make sense in the context of `histoire`.
---
=> fix(nuxt): disable nuxt app manifest

packages/histoire-plugin-nuxt/src/index.ts
A tiny change to avoid failing Nuxt's ecosystem-ci before release of v3.8, so we can ensure histoire is working well with v3.8
---
=> chore(nuxt): temporarily move to `@ts-ignore`

packages/histoire/package.json, packages/histoire/src/node/bin.ts, packages/histoire/src/node/commands/build.ts, packages/histoire/src/node/commands/dev.ts, packages/histoire/src/node/config.ts, packages/histoire/src/node/context.ts, packages/histoire/src/node/util/find-up.ts, pnpm-lock.yaml
Enable specifying path for histoire config file using `-c` or `--config`
Fixes #167
Also updating `pathe` to latest version as well, enabling the removal of the earlier bug workaround
---
=> feat(config): Enable specifying path for histoire config file

packages/histoire-controls/src/components/radio/HstRadio.vue
In the issue #537, was installed `@tailwindcss/forms` which adds globally styles for `[type="checkbox"], [type="radio"]`, where is `display: inline-block`. Even if in HstRadion was added `htw-hidden`, it didn't have enough specificity to overwrite. So, I added "!" to make it important.
Fixes #537 
I would say, my fix is not the perfect one but it at least fixes temporarily the issue. I understand that TailwindCSS speed up development, but it brings problems for users who already use Tailwind and the applied class can be easily overwritten by a stronger specificity selector. I think it should be reviewed the styles appliance and isolation (e.g. scoped style)
---
=> fix: force display none for HstRadio (fix #537)

packages/histoire-plugin-nuxt/src/index.ts
A change coming in Nuxt 2.8.1, we now granularly inject composable auto-imports (https://github.com/nuxt/nuxt/pull/23951) so there is not a single app preset. The change in this PR should be backward compatible.
---
=> fix(nuxt): support multiple app presets

packages/histoire-app/src/app/util/tooltip.ts
Due to missing parameter name TS error appeared:
`'boolean' is an unused renaming of 'isMac'. Did you intend to use it as a type annotation?`
---
=> types: Fix keyboardShortcut param

packages/histoire-plugin-nuxt/src/index.ts
Disable nuxt `typeCheck` feature
fixes #632
---
=> fix(nuxt): disable typescript `typeCheck` (fix #632)

packages/histoire-plugin-vue/components.d.ts
infer `Story` & `Variant` slots `state`, based on `initState`
#622 
---
=> types: add type inference for `Story` and `Variant` slots items (fixes #622)

packages/histoire/src/node/server.ts, packages/histoire/src/node/vite.ts
Fixes #528 #445
HMR was not working with Nuxt (Vue3 however was able to do HMR). 
I'm not a Vite expert, so any help would be appreciated if I misinterpreted the way how histoire is working.
* Previously even for build command HMR was turned on for client builds. Using the `command === 'build'` check in build command HMR is turned off
* For dev builds ('serve'), two vite servers are being launched. First the "normal" one and second the "node server" I believe for collecting the stories. However for the node server HMR is disabled. I _believe_ this has disabled/interfered with the HMR of the first vite server. Changing the launch order makes HMR work for Nuxt as well.
If there is a better way to achieve the same, let me know.
---
=> fix(hmr): Make HMR work with Nuxt

packages/histoire-plugin-vue/src/client/app/MountStory.ts, packages/histoire-plugin-vue/src/client/app/RenderStory.ts, packages/histoire/src/node/server.ts
When using a Wrapper component the browser log was showing a number of warnings when mounting and rendering Wrapper components. 
```
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance. 
```
See repro here:
https://stackblitz.com/edit/nuxt-starter-wdpsex
Open Dev Tools to see the warnings in the browser console
This PR aims to fix that by using `() =>` function slots eliminating the warning
---
=> fix: Fix Vue warning 'Non-function value encountered'

packages/histoire-controls/src/components/button/HstButton.story.vue, packages/histoire-controls/src/components/design-tokens/HstColorShades.story.vue, packages/histoire-controls/src/components/design-tokens/HstColorShades.vue, packages/histoire-controls/src/components/design-tokens/HstTokenList.story.vue
The CI builds are failing due to a few type errors.  This PR is aiming to fix that by adding type annotations
---
=> ci: fix type errors

packages/histoire-app/src/app/util/sandbox.ts
Fixes #635
Vite's base attribute was not properly considered when generating URLs for stories in single / iframe layout.
---
=> fix: Fix sandbox URL in getSandboxUrl function

packages/histoire/src/node/dom/env.ts
Add mock ResizeObserver to DOM after jsdom initialization to fix issue #426 
Using the `@formkit/autoanimate` module makes stories fail on load, since ResizeObserver is missing. The lib itself diligently checks if there is a window object available, before it tries to use it. I checked the relevant issue in Jsdom project ( https://github.com/jsdom/jsdom/issues/3368 ), but most use cases there seemed to be with testing. For those cases, it makes sense to add your own mock, if you want to trigger `observe` in a test. For us, however, it seems a simple noop replacement will do the trick. Hence this PR
---
=> fix: issue 426, add mock ResizeObserver to dom

packages/histoire-shared/src/state.ts
Fix #512 
We shouldn't sync computed state properties. However, I didn't find a proper way to detect if a prop is computed or not (IsReadonly doesn't seem to work).
I think it's okay to silently try/catch the setter, as computed should not be synced anyway.
If you have a better way of only skipping computed props, that would probably be better.
---
=> fix: Silent throw for state sync (fix #512)

packages/histoire-plugin-nuxt/src/index.ts
Fix import preset accessing when the preset does not have a `from` field
Closes #671
---
=> fix(nuxt): import preset access in nuxt

packages/histoire-plugin-vue/src/client/app/RenderStory.ts
Fixes https://github.com/histoire-dev/histoire/issues/677
Added a root to present Suspense failing if there are several root to a story.
⚠️ I'm not quite sure why you would use a factory function for the last argument of the `h()` function...
I took the liberty of removing it, but if it was useful, I'll put it back!
ℹ️ The examples/vue3 project can't reproduce this error because it uses a global wrapper `addWrapper(WrapperGlobal)`
---
=> fix: Add a story root wrapper for Suspense (fix #677)

packages/histoire-plugin-vue/src/client/codegen.ts
Fixes #686
Adds a truthy-ness check before accessing object with `in` operator.
---
=> fix(vue): codegen: check before using `in` on nullable object

packages/histoire-app/src/app/util/sandbox.ts
Reverts histoire-dev/histoire#652
Fix stories in iframes not showing when the base have a slash at the end.
The base url should have a slash at the start and at the end (every guides for configuring the base url have them, for example : https://vitejs.dev/config/shared-options.html#base)
If the base doesn't have the slash at the end, the build produce a bad result, it doesn't find js and css files because a slash is missing in the urls
=> fix: revert "fix: Fix sandbox URL in getSandboxUrl function"

packages/histoire-vendors/rollup.config.mjs
When building @histoire/vendors the generated `d.ts` files were saved with `\n` line endings. On Windows this resulted that these files were showing up as "changed". Using platform specific line endings solves this problem.
---
=> fix: Consider platform specific CRLF when generating d.ts files

packages/histoire-app/src/app/components/story/StoryResponsivePreview.vue
fix the preview that could not being visually resized vertically.
it's a problem that could not appear because two rules have equals css specificity.
---
=> fix: StoryResponsivePreview vertical resize

packages/histoire-app/src/app/components/story/StoryResponsivePreview.vue
Re-add htw-h-full on a div of StoryResponsivePreview like before only when a height is not defined
---
=> fix: StoryResponsivePreview full height

packages/histoire-shared/src/types/config.ts
According to [the example config in the docs](https://histoire.dev/reference/config.html#responsivepresets) its possible to set `height: null` which currently results in an error:
---
=> fix: Make ResponsivePreset.height Type Nullable

packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts
Fixes #667
When using ESMs `export default` instead of `module.exports` in `tailwind.config.{js,ts}` the tailwindConfig is nested in a `default` key which then incorrectly merges with tailwinds default config like this:
---
=> fix: Handle ESM Tailwindconfigs (fix #667)

packages/histoire/src/node/build.ts
This PR adds `optimizeDeps.include = []` and `optimizeDeps.noDiscovery = true` when using vite-node to make histoire pass the tests with Vite with the Environment API PR merged (https://github.com/vitejs/vite/pull/16471).
Setting these options is [recommended by vite-node](https://github.com/vitest-dev/vitest/blob/v0.34.6/packages/vite-node/README.md#programmatic-usage). (`optimizeDeps.disable` is now [deprecated and replaced with the options above](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-disabled).)
`optimizeDeps.noDiscovery` was added in Vite 5.1, but given that histoire works without that setting for Vite pre-6, using it should be fine.
---
=> feat: disable optimizer in vite-node for vite 6 compat

packages/histoire-plugin-nuxt/src/index.ts
Not quite sure why/when this popped up but noticed it failing in CI.
We hope to add an option to more easily configure this in Nuxt itself via https://github.com/nuxt/nuxt/pull/30332.
---
=> fix(nuxt): do not auto-import idle callback polyfills

.github/workflows/test-nuxt3.yml, .github/workflows/test-svelte4.yml, .github/workflows/test-vue3.yml, .github/workflows/test.yml, examples/sveltekit/package.json, examples/vue3-percy/package.json, examples/vue3-screenshot/package.json, examples/vue3-themed/package.json, examples/vue3-vuetify/package.json, examples/vue3/package.json, package.json, packages/histoire-app/package.json, packages/histoire-controls-stories/package.json, packages/histoire-controls/package.json, packages/histoire-plugin-nuxt/package.json, packages/histoire-plugin-vue/package.json, packages/histoire-shared/package.json, packages/histoire/package.json, packages/histoire/src/node/build.ts, packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts, packages/histoire/src/node/vite.ts, pnpm-lock.yaml
Fix https://github.com/histoire-dev/histoire/issues/798, https://github.com/histoire-dev/histoire/issues/792
Update to Vite 7 and update vite-node.
=> feat: Add Vite 7 support

examples/vue3/package.json, packages/histoire/src/node/bin.ts, packages/histoire/src/node/commands/dev.ts, packages/histoire/src/node/server.ts
When I ssh remote development, I need it to be able to expose the service to the LAN to facilitate my debugging
=> feat: add host config to histoire dev

docs/guide/config.md, packages/histoire/src/node/server.ts
Fix https://github.com/histoire-dev/histoire/issues/805
CommonJS modules must be include for Vite to convert them to ESM.
---
=> feat: Add CommonJS support

packages/histoire-shared/src/types/plugin.ts, packages/histoire/src/node/vite.ts
The goal is to allow the injection of vite plugin for histoire. For example, if I want to manipulate the head of the page before the module is mounted.
Example:
```ts
{
name: 'inject-plugin',
vitePlugins(plugins) {
plugins.push({
name: 'html-transform',
transformIndexHtml(html) {
return html.replace(
/<title>(.*?)<\/title>/,
`<title>Title replaced!</title>`,
)
},
})
},
}
```
Note: The particular usecase I'm thinking of, is to be able to inject importmap before module load.
---
=> feat: Add plugin API hook vitePlugins

packages/histoire-plugin-vue/package.json
Using triple-slash TS directives like
```ts
/// <reference types="@histoire/plugin-vue/components" />
```
is not working with my repo and its inclusion of Histoire because the components definition file is not explicitly exposed in the `@histoire/plugin-vue` library's package.json. These component types are also not exposed via the default type export (`./dist/index.node.d.ts`), so they are unable to be referenced in modern repo setups. This change rectifies that issue.
=> types: Update `histoire-plugin-vue` to expose `components.d.ts`
